{-
  The sequence of triangle numbers is generated by adding the natural numbers.
  So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first
  ten terms would be:

      1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

  Let us list the factors of the first seven triangle numbers:

      1: 1
      3: 1,3
      6: 1,2,3,6
     10: 1,2,5,10
     15: 1,3,5,15
     21: 1,3,7,21
     28: 1,2,4,7,14,28
  
  We can see that 28 is the first triangle number to have over five divisors.

  What is the value of the first triangle number to have over five hundred
  divisors?
-}

module Main where
import Euler
import Data.List

main = putStrLn $ show $ ans 500

ans n = head [ i | i <- triangles, n < divisors i ]

divisors n = foldl (*) 1 $ map (\x -> 1 + snd x) $ primeFactorisation n

triangles = map triangle [1..]
  where
    triangle 1 = 1
    triangle n = n + triangle (n-1)

primeFactorisation n = map gather $ nub $ primeFactors n
  where gather f = (f, length $ filter (==f) $ primeFactors n)
